package com.campany.aws.elasticsearch.general;

public class Constants {

	public static final String ES_SERVICE_NAME = "es";
	public static final String AES_ENDPOINT = "https://search-monitoring-wofzij55qsje7pj3dgx7mmrlzm.eu-central-1.es.amazonaws.com";
	public static final String INDEX_NAME = "vehicle";
	public static final String INDEXING_PATH = "/" + INDEX_NAME + "/doc";
	public static final String MAPPING_PATH = "/" + INDEXING_PATH + "/_mappings";
	public static final String S3_SERVICE_NAME = "s3";
	public static final String REGION = "eu-central-1";
	public static final String BUCKET_NAME = "elasticsearch-snapshots-test";
	public static final String SERVICE_ROLE = "arn:aws:iam::275795293178:role/s3-to-elasticsearch-role";
	public static final String KibanaSavedObjectMeta_searchSourceJSON_Search_ID = "e9b11c60-854b-11e8-aa36-d3d1ebe813fd";
	public static final String KibanaSavedObjectMeta_searchSourceJSON_Search_ID_VEHICLE_INDEX = "d0190d80-94be-11e8-aa36-d3d1ebe813fd";
	public static final String BASE_URL_LOCAL = "http://localhost:9200";
	public static final String IFRAME_AREA_DIAGRAMM = "<iframe src=\"https://search-monitoring-wofzij55qsje7pj3dgx7mmrlzm.eu-central-1.es.amazonaws.com/_plugin/kibana/app/kibana#/visualize/edit/7d7fdba0-8b61-11e8-aa36-d3d1ebe813fd?embed=true&_g=()&_a=(filters:!(),linked:!f,query:(language:lucene,query:''),uiState:(vis:(colors:('Co2+Austo%C3%9F':%23B7DBAB,'Co2+Austo%C3%9F+(g%2FKm)':%23EA6460),legendOpen:!t)),vis:(aggs:!((enabled:!t,id:'1',params:(customLabel:'Co2+Austo%C3%9F+(g%2FKm)',field:CO2-Ausstoss.bis),schema:metric,type:avg),(enabled:!t,id:'2',params:(field:registrationDate_yy-mm-dd,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:_term,otherBucket:!f,otherBucketLabel:Other,size:1000000),schema:segment,type:terms),(enabled:!t,id:'3',params:(customLabel:'Leistung+(PS)',field:Leistung.bis),schema:metric,type:avg)),params:(addLegend:!t,addTimeMarker:!f,addTooltip:!t,categoryAxes:!((id:CategoryAxis-1,labels:(filter:!t,fontSize:20,rotate:75,show:!t,truncate:20),position:bottom,scale:(type:linear),show:!t,style:(),title:(),type:category)),grid:(categoryLines:!t,style:(color:%23eee)),legendPosition:right,seriesParams:!((data:(id:'1',label:'Co2+Austo%C3%9F+(g%2FKm)'),drawLinesBetweenPoints:!t,interpolate:linear,mode:stacked,show:true,showCircles:!t,type:area,valueAxis:ValueAxis-1),(data:(id:'3',label:'Leistung+(PS)'),drawLinesBetweenPoints:!t,interpolate:linear,mode:stacked,show:!t,showCircles:!t,type:area,valueAxis:ValueAxis-1)),times:!(),type:area,valueAxes:!((id:ValueAxis-1,labels:(filter:!f,fontSize:20,rotate:0,show:!t,truncate:100),name:LeftAxis-1,position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Co2+Austo%C3%9F'),type:value))),title:Area_visualization,type:area))\" height=\"600\" width=\"800\"></iframe>";
	public static final String IFRAME_LINE_DIAGRAMM = "<iframe src=\"https://search-monitoring-wofzij55qsje7pj3dgx7mmrlzm.eu-central-1.es.amazonaws.com/_plugin/kibana/app/kibana#/visualize/edit/b56f9a5c-d7e5-4bcb-843e-336056b67124?embed=true&_g=()&_a=(filters:!(),linked:!f,query:(language:lucene,query:''),uiState:(vis:(colors:('Leistung+(PS)':%23E24D42,Letzter-Neupreis:%237CFC00))),vis:(aggs:!((enabled:!t,id:'1',params:(customLabel:'',field:Letzter-Neupreis.bis),schema:metric,type:avg),(enabled:!t,id:'3',params:(customLabel:Auftrittsdatum,field:registrationDate_yy-mm-dd,missingBucket:!f,missingBucketLabel:Missing,order:asc,orderBy:_term,otherBucket:!f,otherBucketLabel:Other,size:1000000000),schema:segment,type:terms),(enabled:!t,id:'4',params:(customLabel:'Leistung+(PS)',field:Leistung.bis),schema:metric,type:avg)),params:(addLegend:!t,addTimeMarker:!f,addTooltip:!t,categoryAxes:!((id:CategoryAxis-1,labels:(filter:!t,fontSize:15,rotate:75,show:!t,truncate:100),position:bottom,scale:(type:linear),show:!t,style:(),title:(),type:category)),grid:(categoryLines:!f,style:(color:%23eee),valueAxis:ValueAxis-1),legendPosition:top,orderBucketsBySum:!f,seriesParams:!((data:(id:'1',label:Letzter-Neupreis),drawLinesBetweenPoints:!t,interpolate:linear,lineWidth:3,mode:normal,show:true,showCircles:!t,type:line,valueAxis:ValueAxis-1),(data:(id:'4',label:'Leistung+(PS)'),drawLinesBetweenPoints:!t,interpolate:linear,lineWidth:2,mode:normal,show:!t,showCircles:!t,type:line,valueAxis:ValueAxis-1)),times:!(),type:line,valueAxes:!((id:ValueAxis-1,labels:(filter:!f,fontSize:15,rotate:0,show:!t,truncate:100),name:LeftAxis-1,position:left,scale:(defaultYExtents:!f,mode:normal,setYExtents:!f,type:log),show:!t,style:(),title:(text:''),type:value))),title:_line_diagram_X_Auftrittsdatum_Y_Letzter-Neupreis.bis_Y_Leistung.bis_test_,type:line))\" height=\"600\" width=\"800\"></iframe>";
	// public static final String DASHBOARD_SHAREABLE_LINK =
	// "https://search-monitoring-wofzij55qsje7pj3dgx7mmrlzm.eu-central-1.es.amazonaws.com/_plugin/kibana/app/kibana#/dashboard/${dashboard-uuid}?_g=()";
	public static final String DASHBOARD_SHAREABLE_LINK = "https://search-monitoring-wofzij55qsje7pj3dgx7mmrlzm.eu-central-1.es.amazonaws.com/_plugin/kibana/app/kibana#/dashboard/${dashboard-uuid}?_g=(refreshInterval%3A('%24%24hashKey'%3A'object%3A192'%2Cdisplay%3A'5%20seconds'%2Cpause%3A!f%2Csection%3A1%2Cvalue%3A5000)%2Ctime%3A(from%3Anow-15m%2Cmode%3Aquick%2Cto%3Anow))";
	public static final String DASHBOARD_SHAREABLE_EMBEDDED_IFRAME = "<iframe src=\"https://search-monitoring-wofzij55qsje7pj3dgx7mmrlzm.eu-central-1.es.amazonaws.com/_plugin/kibana/app/kibana#/dashboard/${dashboard-uuid}?embed=true&_g=(refreshInterval%3A('%24%24hashKey'%3A'object%3A192'%2Cdisplay%3A'5%20seconds'%2Cpause%3A!f%2Csection%3A1%2Cvalue%3A5000)%2Ctime%3A(from%3Anow-15m%2Cmode%3Aquick%2Cto%3Anow))\" height=\"${iframe-height}\" width=\"${iframe-width}\"></iframe>";
}
